<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWbs5yrc\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWbs5yrc/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerWbs5yrc.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerWbs5yrc\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerWbs5yrc\appProdProjectContainer([
    'container.build_hash' => 'Wbs5yrc',
    'container.build_id' => 'e1efa6ca',
    'container.build_time' => 1604259872,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWbs5yrc');
